[package]
name = "dbc-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.0"
dotenv = "0.15.0"
poise = "0.5.5"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.183", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full", "signal"] }
serde_json = "1.0.105"
chrono = "0.4.26"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
futures = "0.3.28"
