[package]
name = "dbc-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
poise = "0.5.5"
sqlx = "0.7.1"
tokio = { version = "1.30.0", features = ["rt-multi-thread"] }
