version: '3'
services:
  dbc-bot:
    image: shawnpandev/dbc-bot
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      BRAWL_STARS_TOKEN: ${BRAWL_STARS_TOKEN}
    volumes:
      - /etc/ssl/certs/:/etc/ssl/certs:ro
    build: 
      context: .
      dockerfile: Dockerfile
